Fitur untuk tambah, ubah, hapus, dan tampilkan notifikasi
OpenSID/tracksid pull request #12
Opened 2020-08-24 11:07 UTC by masumo

Perubahan terkait issue #4 #5 #6

2020-08-27 12:11 UTC, eddieridwan requested changes
@masumo terima kasih. Script ini masih bersifat hasil template CI, dan perlu disesuaikan dengan aturan penulisan kita. Seluruh TrackSID perlu disesuaikan, tapi bisa mulai dengan script tambahan.

Dan gaya tampilan perlu juga disesuaikan dengan tampilan standar OpenSID -- kecuali kalau ada usul tampilan admin yg lebih baik. Tampilan seluruh TrackSID perlu dibuat konsisten. Tapi bisa mulai dengan script yg baru ditambah. Mungkin bung @afa28 ada usul gaya tampilan modul admin yg lebih baik (dibanding OpenSID)?

Supaya kita bisa kerjakan bersama, saya telah masukkan ke branch `notifikasi`. Dan anda beserta @afa28 telah saya invite ikut tim yg bisa push langsung ke branch tersebut. 

Jadi @masumo  dan @afa28 silakan lakukan perubahan/perbaikan langsung di branch `notifikasi`. Nanti kalau sudah stabil, baru digabungkan ke branch `master`.

2020-08-27 12:12 UTC, eddieridwan commented
@masumo jadi pull request ini ditutup saja, dan teruskan pengembangan menu notifikasi langsung di branch `notifikasi`.

2020-08-27 12:25 UTC, eddieridwan commented
@masumo Perlu perbaikan form notifikasi. Dan perlu tambahkan validasi di form (jquery validasi).

![pilihan-notifikasi](https://user-images.githubusercontent.com/249563/91441489-a4ce6080-e8b3-11ea-973e-9508917fba95.jpg)

2020-08-27 13:01 UTC, afa28 commented
> @masumo terima kasih. Script ini masih bersifat hasil template CI, dan perlu disesuaikan dengan aturan penulisan kita. Seluruh TrackSID perlu disesuaikan, tapi bisa mulai dengan script tambahan.
> 
> Dan gaya tampilan perlu juga disesuaikan dengan tampilan standar OpenSID -- kecuali kalau ada usul tampilan admin yg lebih baik. Tampilan seluruh TrackSID perlu dibuat konsisten. Tapi bisa mulai dengan script yg baru ditambah. Mungkin bung @afa28 ada usul gaya tampilan modul admin yg lebih baik (dibanding OpenSID)?
> 
> Supaya kita bisa kerjakan bersama, saya telah masukkan ke branch `notifikasi`. Dan anda beserta @afa28 telah saya invite ikut tim yg bisa push langsung ke branch tersebut. 
> 
> Jadi @masumo  dan @afa28 silakan lakukan perubahan/perbaikan langsung di branch `notifikasi`. Nanti kalau sudah stabil, baru digabungkan ke branch `master`.
> 

Bisa pakai template gentelella. Tp klw sdah terbiasa dgn template adminlte mending jgn diubah, cuma dibedakan sj view untuk public dan admin. Misal, untuk view untuk ditampilkan di public bisa pakai yg layout top navigation.

2020-09-03 10:23 UTC, eddieridwan commented
@masumo terima kasih. Sdh digabung ke `master` setelah dikembangkan lebih lanjut

2020-09-03 10:23 UTC, closed without merging