RESTful API SERVER - PANTAU OPENSID
OpenSID/tracksid pull request #15
Opened 2020-10-21 09:04 UTC by fusionid

### RESTful API SERVER - PANTAU OPENSID

**A. API PELANGGAN PREMIUM**

1. Data Seluruh Pelanggan Premium (Akses Admin)
https://pantau.opensid.my.id/index.php/api/pelanggan/admin?token={TOKEN-ADMIN}

2. Data Pelanggan Premium Berdasarkan ID Pelanggan (Akses Admin)
https://pantau.opensid.my.id/index.php/api/pelanggan/admincs?token={TOKEN-ADMIN}&id={ID-PELANGGAN}

3. Data Pelanggan Premium Yg Bisa Dilihat Pelanggan (Akses Pelanggan)
https://pantau.opensid.my.id/index.php/api/pelanggan/customer?id={ID-PELANGGAN}&token={TOKEN-PELANGGAN}

**B. API PENGGUNA**

1. Data Seluruh Pengguna (Akses Admin)
https://pantau.opensid.my.id/index.php/api/user/admin?token={TOKEN-ADMIN}

2. Data Pengguna Berdasarkan ID Pengguna (Akses Admin)
https://pantau.opensid.my.id/index.php/api/user/admincs?token={TOKEN-ADMIN}&id={ID-PENGGUNA}

3. Data Pengguna Yg Bisa Dilihat Pengguna (Akses Pengguna)
https://pantau.opensid.my.id/index.php/api/user/customer?id={ID-PENGGUNA}&token={TOKEN-PENGGUNA}

**C. API KODE WILAYAH (Akses Publik)**

1. Data Seluruh Kode Wilayah
https://pantau.opensid.my.id/index.php/api/wilayah/all

2. Data Kode Wilayah Berdasarkan Nama Provinsi
https://pantau.opensid.my.id/index.php/api/wilayah/namaprov?nama={NAMA-PROVINSI}

3. Data Kode Wilayah Berdasarkan Kode Provinsi
https://pantau.opensid.my.id/index.php/api/wilayah/kodeprov?kode={KODE-PROVINSI}

4. Data Kode Wilayah Berdasarkan Nama Kabupaten
https://pantau.opensid.my.id/index.php/api/wilayah/namakab?nama={NAMA-KABUPATEN}

5. Data Kode Wilayah Berdasarkan Kode Kabupaten
https://pantau.opensid.my.id/index.php/api/wilayah/kodekab?kode={KODE-KABUPATEN}

6. Data Kode Wilayah Berdasarkan Nama Kecamatan
https://pantau.opensid.my.id/index.php/api/wilayah/namakec?nama={NAMA-KECAMATAN}

7. Data Kode Wilayah Berdasarkan Kode Kecamatan
https://pantau.opensid.my.id/index.php/api/wilayah/kodekec?kode={KODE-KECAMATAN}

8. Data Kode Wilayah Berdasarkan Nama Desa
https://pantau.opensid.my.id/index.php/api/wilayah/namadesa?nama={NAMA-DESA}

9. Data Kode Wilayah Berdasarkan Kode Desa
https://pantau.opensid.my.id/index.php/api/wilayah/kodedesa?kode={KODE-DESA}

**GENERATE TOKEN / API KEY :**
1. API KEY Admin dan Pengguna 
https://pantau.opensid.my.id/tracksid/index.php/user -> Aksi -> Ubah -> Generate Key
![generate_api_admin](https://user-images.githubusercontent.com/10391199/96697365-098ad080-13b6-11eb-93a0-1313d4cce7ba.PNG)

2. API KEY Pelanggan Premium 
https://pantau.opensid.my.id/tracksid/index.php/pelanggan -> Aksi -> Ubah Data -> Generate Key
![generate_api_pelanggan](https://user-images.githubusercontent.com/10391199/96697411-17405600-13b6-11eb-9512-ab88f12484b0.PNG)

**TESTING RESPONSE API SERVER :**
Menggunakan aplikasi POSTMAN https://www.postman.com/downloads/
- Metode Request : GET
- KEY dan VALUE dientry ke PARAMS 
KEY = token, id, nama, kode
VALUE = TOKEN ADMIN, TOKEN PENGGUNA, ID PELANGGAN, ID PENGGUNA, NAMA dan KODE PROVINSI / KABUPATEN / KECAMATAN / DESA
![postman](https://user-images.githubusercontent.com/10391199/96697511-3343f780-13b6-11eb-8237-3ba0305f53ed.PNG)

2020-10-22 07:08 UTC, eddieridwan reviewed
@fusionid terima kasih.

Ada banyak file yg hanya berubah whitespace atau ganti chmode (lebih dari 100). Jadi sulit untuk me-review file mana saja yg perlu diteliti. 

Lihat komentar. Mohon jelaskan rancangan konsep apa lagi yang anda ubah atau terapkan -- supaya lebih mudah direview.

2020-10-22 07:08 UTC, eddieridwan commented on application/migrations/20201020000010_restful_api.php
> +    $this->db->close();
Mengapa dibuat tabel wilayah baru? Datanya dari mana? 
Dan mengapa menggunakan struktur duplikasi wilayah sehingga jadi besar -- dan lebih sulit kalau ada yang perlu diubah (misalnya ada ejaan yg perlu diubah)?

Apakah tidak bisa buat API yg menggunakan struktur yg ada?

2020-10-22 07:12 UTC, fusionid commented on application/migrations/20201020000010_restful_api.php
> +		}
> @Fusion, mengapa menggunakan kategori grup dari OpenSID? Apakah ini dimaksud sebagai grup untuk TrackSID?

Ini hanya sekedar buat tampilkan form user saja dengan mengambil format yg sudah ada di opensid, fokusnya masih di api belum ke form. Nanti dirubah total formnya.

2020-10-22 07:22 UTC, fusionid commented on application/migrations/20201020000010_restful_api.php
> +    $this->db->close();
Kode wilayah ada di tabel baru ->i "kode_wilayah", bisa diimport file sqlnya di application/migrations/kode_wilayah.sql. Datanya dari Permendagri no 72 tahun 2019.
Struktur db bisa di rubah dan di split parent-child, tapi supaya tidak banyak query untuk grab data maka disatukan dulu.

2020-10-22 07:45 UTC, fusionid commented
> @fusionid terima kasih.
> 
> Ada banyak file yg hanya berubah whitespace atau ganti chmode (lebih dari 100). Jadi sulit untuk me-review file mana saja yg perlu diteliti.
> 
> Lihat komentar. Mohon jelaskan rancangan konsep apa lagi yang anda ubah atau terapkan -- supaya lebih mudah direview.

Kemarin coba commit lewat git di windows, ada “warning: LF will be replaced by CRLF” di ignore dan sepertinya hasilnya jadi error, akhirnya di re-commit lagi di ubuntu.

Library yg dipakai :
RestServer -> https://github.com/chriskacerguis/codeigniter-restserver
Token encode and decode JWT -> https://github.com/firebase/php-jwt

API ini bisa digunakan untuk berbagai tujuan user, salah satunya untuk OpenSID Pelanggan Premium. 
Jika API Key/Token sudah diisi di menu pengaturan (seperti kolom Mapbox Token) di OpenSID, maka komunikasi dua arah sudah terhubung, 
Di OpenSID Pengguna bisa melihat profilenya yg berisi data2 pengguna seperti masa berlaku langganan dll. 
Pengguna juga bisa merubah data lainnya yg diizinkan untuk dirubah seperti nama desa dll.

2020-10-22 10:01 UTC, eddieridwan commented on application/migrations/20201020000010_restful_api.php
> +    $this->db->close();
Hasilnya ada dua tabel wilayah yg berbeda isinya -- yg akan bermasalah. Sebaiknya tabel `tbl_regions` yg sdh ada diupdate ke Permendagri no 72 2019, dengan mempertahankan struktur supaya fitur TrackSID yg ada bisa tetap jalan. Dan tetap konsisten dengan kode desa yg ada di tabel `desa`.

2020-10-22 10:04 UTC, eddieridwan commented
Bagaimana menghindari API key pelanggan tidak digunakan oleh pengguna lain? Bagaimana mengikat API key tersebut ke desa yg berhak saja?

2020-10-22 10:23 UTC, eddieridwan requested changes
@fusionid mohon lihat komentar

2020-10-22 10:23 UTC, eddieridwan commented on application/migrations/20201020000010_restful_api.php
> +		}
@fusionid ini gagal, karena tabel `pelanggan` sudah ada. Mengapa membuat tabel `pelanggan` baru?

2020-10-22 10:23 UTC, eddieridwan commented on application/migrations/20201020000010_restful_api.php
> +		}
Ini gagal karena `fields[]` berperan menambah ke array. Array itu masih berisi field `token` untuk `pelanggan`. Jadi akan diulangi -- sehingga error duplicate field.

2020-10-22 10:25 UTC, fusionid commented on application/migrations/20201020000010_restful_api.php
> +		}
Typo maksudnya tabel 'user_grup'

2020-10-22 10:35 UTC, fusionid commented
> Bagaimana menghindari API key pelanggan tidak digunakan oleh pengguna lain? Bagaimana mengikat API key tersebut ke desa yg berhak saja?

1. Login hanya bisa dari API Key + IP terdaftar , kelemahan : tidak ada mobilitas, hanya bisa diakses dalam jaringannya.
2. Login hanya bisa dari API Key + Pelanggan ID
3. Login hanya bisa dgn API Key + 2FA (2-Factor Authentication) dgn pilihan metode :
- Hardware Tokens
- SMS Text-Message and Voice-based
- Software Tokens
- Push Notification
- Biometric

No. 2 bisa diterapkan dan mudah serta tidak menyulitkan pelanggan
No. 3 belum ada library yg opensource

Pilihan Generate/Reset API :
1. Hanya Admin
2. Admin dan Pelanggan

Tapi semuanya kembali ke pelanggan untuk tetap berkewajiban menjaga kerahasiaan api key.

2020-10-22 10:45 UTC, eddieridwan commented
API Wilayah d TrackSID tidak ingin kita buka bagi publik, karena akan memberatkan sistem dan bukan misi kita. API WIlayah dan semua API TrackSID dimaksudkan hanya digunakan untuk mendukung OpenSID saja.

2020-10-22 10:49 UTC, eddieridwan commented
> Tapi semuanya kembali ke pelanggan untuk tetap berkewajiban menjaga kerahasiaan api key.

Sepertinya kita tidak bisa andalkan ini. Dari pengalaman, pelanggan tidak bisa dijamin etikanya. Jadi kita perlu ada cara untuk menjaga tidak digunakan kecuali oleh yg berhak.

2020-10-22 10:58 UTC, eddieridwan commented on application/migrations/20201020000010_restful_api.php
> +    $this->db->close();
@fusionid Tabel wilayah berdasarkan Permendagri no 72 tahun 2019 diambil dari acuan mana (urlnya apa)?

2020-10-22 12:41 UTC, fusionid commented on application/migrations/20201020000010_restful_api.php
> +    $this->db->close();
https://www.kemendagri.go.id/files/2020/PMDN%2072%20TH%202019+lampiran.pdf -> Diolah kedalam excel dari halaman 8 s/d 3924 -> https://github.com/OpenSID/OpenSID/files/5395654/kode_wilayah_administratif_pmdn72_2019.xlsx -> Diconvert ke csv -> Diconvert ke sql

2020-10-23 09:18 UTC, eddieridwan commented
@fusionid , saya sudah gunakan data yg anda sediakan di `application/migrations/kode_wilayah_permendagri_72_2019.sql` dan update tabel `tbl_regions`. Sudah di `master` dan di pasang di pantau.opensid.my.id. Jadi API Wilayah sekarang bisa diubah mengambil data dari `tbl_regions`.

2020-10-25 10:52 UTC, eddieridwan reviewed
@fusionid terima kasih.

Tapi mohon anda paham bahwa pull request anda ini menyusahkan. Karena berisi terlalu banyak perubahan, sehingga sulit direview. Dan juga berisi banyak copy paste sebagai pengembangan sementara yg saya mengerti akan diperbaiki kemudian. Tapi sebagai proses untuk menggabungkan ke `master` akan membuat `master` tidak stabil. 

Di satu pihak, penambahan fitur API anda sangat membantu, tapi perlu dipertimbangkan ketidak-stabilan dari penambahan yg lain yg masih bersifat setengah jadi dan sulit direview.

Saya akan gabungkan, karena fitur API memang diperlukan. Tapi script yg masih setengah jadi perlu segera diperbaiki. 

`Mohon dengan sangat untuk PR berikutnya, setiap PR batasi ke satu fitur saja`. Proses pengembangan secara `agile` yg kita lakukan mengharuskan kita lakukan dengan langkah kecil2, secara iteratif. Tidak sekaligus banyak yg diubah atau ditambah. Perubahan besar2 justru memperlambat. 

Bung @afa28 , mohon perhatian anda juga. Terima kasih, anda sekarang sdh mulai terbiasa mengirim PR kecil2.

Terima kasih, teman2.

2020-10-25 11:15 UTC, eddieridwan commented
@fusionid saya sdh gabung ke `master` (commitnya di-squash). 

Jadi branch ini bisa ditutup. Dan sekali lagi, mohon PR berikutnya kecil2 saja supaya lebih mudah direview. Dan mohon juga kurangi text editor anda melakukan perubahan secara otomatis hanya menyesuaikan whitespace saja. Kecuali memang file tidak mengikuti aturan -- dan batasi hanya pada file yg berhubungan dengan PR saja.

2020-10-25 11:41 UTC, closed without merging