bersihkan data akses
OpenSID/tracksid pull request #46
Opened 2022-03-14 15:49 UTC by FirlianiF

https://github.com/OpenSID/tracksid/issues/43

2022-04-02 12:45 UTC, andifahruddinakas requested changes

2022-04-02 12:45 UTC, andifahruddinakas commented on app/Http/Controllers/AksesController.php
> +    public function bersihkan()
Gunakan invoke

2022-04-05 00:47 UTC, FirlianiF commented on app/Http/Controllers/AksesController.php
> +    public function bersihkan()
sudah di update,  dicek mas

2022-04-05 06:12 UTC, agungsugiarto reviewed
Lihat hasil review

2022-04-05 06:12 UTC, agungsugiarto commented on app/Models/Akses.php
> +    }
Tujuan konversi ke laravel sekaligus memperbaiki proses alur sebuah code, jangan gunakan proses seperti ini, mohon disederhanakan.

2022-04-05 06:12 UTC, agungsugiarto commented on app/Models/Desa.php
> +    }
Gunakan standar penulisan mengikuti [PSR2](https://www.php-fig.org/psr/psr-2)

2022-04-05 06:12 UTC, agungsugiarto commented on routes/web.php
> +    });
Gunakan middleware

2022-04-18 04:27 UTC, FirlianiF commented
Mohon dicek kembali mas @agungsugiarto

2022-04-28 04:51 UTC, andifahruddinakas requested changes

2022-04-28 04:51 UTC, andifahruddinakas commented on app/Models/Akses.php
> +        $keep = Desa::where('desa_id', $desa->id)
@FirlianiF. Ini tidak jalan, $desa->id tidak terdefenisi. Apa sudah di uji coba setelah perubahan?

2022-04-28 04:52 UTC, andifahruddinakas commented on app/Models/Akses.php
> +        $keep = Desa::where('desa_id', $desa->id)
Akses::bersihkan();

2022-05-16 11:31 UTC, FirlianiF commented
sudah di update, dicek mas @andifahruddinakas

2022-05-19 08:57 UTC, merged