Menu pengguna
OpenSID/tracksid pull request #49
Opened 2022-03-17 01:21 UTC by FirlianiF

https://github.com/OpenSID/tracksid/issues/43

2022-04-02 12:50 UTC, andifahruddinakas requested changes

2022-04-02 12:50 UTC, andifahruddinakas commented on routes/web.php
> +        Route::get('get/akun-pengguna', [PenggunaController::class, 'getAkunPengguna'])->name('get.akun-pengguna');
Ganti jadi get('akun-pengguna/datatables')

2022-04-05 00:58 UTC, FirlianiF commented on routes/web.php
> +        Route::get('get/akun-pengguna', [PenggunaController::class, 'getAkunPengguna'])->name('get.akun-pengguna');
sudah di update, dicek mas

2022-04-05 06:14 UTC, agungsugiarto commented on app/Http/Controllers/PenggunaController.php
> +        }
Rubah sesuai standard laravel

```php
$this->validate(...)
```

2022-04-05 06:14 UTC, agungsugiarto commented on app/Http/Controllers/PenggunaController.php
> +        }
Rubah sesuai standard laravel

```php
$this->validate(...)
```

2022-04-05 06:19 UTC, agungsugiarto reviewed
Lihat hasil review

2022-04-10 08:26 UTC, FirlianiF commented
Sudah di perbaiki, di cek mas @agungsugiarto

2022-04-28 05:01 UTC, andifahruddinakas requested changes

2022-04-28 05:09 UTC, andifahruddinakas requested changes

2022-04-28 05:09 UTC, andifahruddinakas commented on app/Http/Controllers/PenggunaController.php
> +        ]);
@FirlianiF. Buat PenggunaRequest untuk pengecekan validasi

2022-05-16 11:01 UTC, FirlianiF commented
Sudah di update, dicek mas @andifahruddinakas

2022-05-23 01:52 UTC, merged