notif
OpenSID/tracksid pull request #50
Opened 2022-03-20 23:49 UTC by FirlianiF

https://github.com/OpenSID/tracksid/issues/43

2022-04-02 12:53 UTC, andifahruddinakas requested changes

2022-04-02 12:53 UTC, andifahruddinakas commented on routes/web.php
> +        Route::get('get/notifikasi', [NotifikasiController::class, 'getNotifikasi'])->name('get.notifikasi');
Masukkan ke group, misalnya notifikasi/datatables stelah route resource.

2022-04-05 01:05 UTC, FirlianiF commented on routes/web.php
> +        Route::get('get/notifikasi', [NotifikasiController::class, 'getNotifikasi'])->name('get.notifikasi');
sudah di update, dicek mas.

2022-04-05 06:16 UTC, agungsugiarto commented on app/Http/Controllers/NotifikasiController.php
> +        }
Rubah sesuai standard laravel

```php
$this->validate(...)
```

Atau gunakan Request https://laravel.com/docs/8.x/validation#form-request-validation

2022-04-05 06:17 UTC, agungsugiarto commented on app/Models/Notifikasi.php
> +        }
Gunakan first or insert

2022-04-05 06:17 UTC, agungsugiarto reviewed
Lihat hasil review

2022-04-10 08:44 UTC, FirlianiF commented
sudah di perbaiki, dicek mas @agungsugiarto

2022-04-11 04:44 UTC, agungsugiarto commented on app/Http/Controllers/Api/TrackController.php
> +            $notif = Notifikasi::get_semua_notif($desa->id);
Gunakan penamaan method sesuai standard psr2

2022-04-11 04:44 UTC, agungsugiarto commented on app/Models/Notifikasi.php
> +    public static function get_semua_notif($id_desa)
Gunakan penamaan method sesuai psr2

2022-04-11 04:44 UTC, agungsugiarto commented on app/Models/Notifikasi.php
> +    public static function non_aktifkan($notif, $id_desa)
Gunakan penamaan method sesuai psr2

2022-04-11 04:44 UTC, agungsugiarto reviewed
Lihat hasil review

2022-04-18 04:38 UTC, FirlianiF commented
Mohon dicek kembali mas @agungsugiarto

2022-04-28 05:07 UTC, andifahruddinakas requested changes

2022-04-28 05:07 UTC, andifahruddinakas commented on app/Http/Controllers/NotifikasiController.php
> +use Illuminate\Support\Facades\Validator;
```suggestion
```

2022-04-28 05:07 UTC, andifahruddinakas commented on app/Http/Controllers/NotifikasiController.php
> +        ]);
@FirlianiF. Buat class Request untuk Notifikasi, validasinya sama.

```
$request->validate([
            'kode' => 'required|max:100',
            'judul' => 'required|max:100',
            'jenis' => 'required',
            'isi' => 'required',
            'input_server' => 'required',
            'frekuensi' => 'required',
            'aktif' => 'required',
        ]);
```

2022-07-30 18:31 UTC, closed without merging